# IMPORTING DATA

In [10]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [11]:
import pandas as pd
data=pd.read_csv('gdrive/My Drive/Colab Notebooks/Code Warriors - 21 Days ML/Model2-IrisClassPrediction-Day18/IRIS.csv')

In [12]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [14]:
data['species'].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: species, dtype: int64

In [15]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [16]:
data.sample(10)

sepal_length  sepal_width  petal_length  petal_width          species
134           6.1          2.6           5.6          1.4   Iris-virginica
75            6.6          3.0           4.4          1.4  Iris-versicolor
140           6.7          3.1           5.6          2.4   Iris-virginica
93            5.0          2.3           3.3          1.0  Iris-versicolor
0             5.1          3.5           1.4          0.2      Iris-setosa
12            4.8          3.0           1.4          0.1      Iris-setosa
141           6.9          3.1           5.1          2.3   Iris-virginica
133           6.3          2.8           5.1          1.5   Iris-virginica
44            5.1          3.8           1.9          0.4      Iris-setosa
54            6.5          2.8           4.6          1.5  Iris-versicolor

# SPLITING DATA INTO FEATURE (INDEPENDENT VAR) AND LABEL (DEPENDENT VAR)

*   x feature - independent variable
*   y label - dependent variable


*   List item
*   List item





In [21]:
x = data.iloc[:,0:4]
print(x.head())

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2


In [22]:
y = data.iloc[:,-1]
print(y.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object


In [23]:
# above x, y in data frame
# we need to convert it into numpy array
print(type(x))

x = x.values
y = y.values

print(type(x))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


# TRANSFORM CATEGORICAL VALUE INTO NUMERIC

In [27]:
from sklearn.preprocessing import LabelBinarizer
# label_binarize perform both one hot encoding as well as label encoding one after another

# label encoding : 0 for male, 1 for female
# one hote encoding : on nth row if male then set-1 else set-0 oor if female place 1 not femal place 0

lb = LabelBinarizer()
y = lb.fit_transform(y)

In [28]:
print(y[0:5, :])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


# SPLITING DATA SET INTO TEST AND TRAIN


In [29]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [30]:
print('training dataset \n')
print('> ', x_train.shape, y_train.shape)

print('\ntesting dataset \n')
print('> ', x_test.shape, y_test.shape)

training dataset 

>  (120, 4) (120, 3)

testing dataset 

>  (30, 4) (30, 3)


In [31]:
print(x_train.shape, y_train.shape)
print('training feature: \n', x_train[:5, :])
print('training label: \n', y_train[:5, :])

(120, 4) (120, 3)
training feature: 
 [[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]]
training label: 
 [[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [33]:
import numpy as np

# this need to done for checking accuracy 
print(y_test[0:5, :])
y_test = np.argmax(y_test, axis=1)
print(y_test)

# similarly we also do with y_pred after getting data

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


# TRAINING MODEL


In [34]:
import numpy as np
from sklearn.metrics import accuracy_score

In [35]:
# RANDOME FOREST - CODE WARRIOR

from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(n_estimators=100)
# n_estimators -> no of tree we want to use

model = rf_classifier.fit(x_train, y_train)
print('model created successfully')

model created successfully


In [ ]:
# DECISION TREE

from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)

model = dt_classifier.fit(x_train, y_train)
print('model created successfully')

model created successfully


In [ ]:
# NAIVE BAYES

from sklearn.naive_bayes import GaussianNB

nb_classifer = GaussianNB()

model = nb_classifer.fit(x_train, y_train)
print('model created successfully')

ValueError: ignored

In [ ]:
# SUPPORT VECTOR MACHINE

from sklearn.svm import SVC

svm_classifier = SVC(kernal='rbf')

model = svm_classifier.fit(x_train, y_train)

print('model created successfully')

TypeError: ignored

In [ ]:
# KNN

from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

model = knn_classifier.fit(x_train, y_train)

print('model created successfully')

model created successfully


In [ ]:
# LOGISTIC REGRESSION

from sklearn.linear_model import LogisticRegression

lr_classifier = LogisticRegression()

model = lr_classifier.fit(x_train, y_train)

print('model created successfully')

ValueError: ignored

# TESTING MODEL

In [ ]:
y_pred = model.predict(x_test)
print(y_pred[0:5, :])
y_pred = np.argmax(y_pred, axis=1)
print(y_pred)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_pred, y_test)
print(cm)
# rest then diagonal are zero then we say 0% error or 100% accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_pred, y_test)
print('accuracy: ', accuracy*100,'%')

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 2 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[[11  0  0]
 [ 0 12  0]
 [ 0  1  6]]
accuracy:  96.66666666666667 %
