# IMPORT DATA SET 

In [60]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [61]:
import pandas as pd 
# data = pd.read_csv("car_data.csv")
# data=pd.read_csv('gdrive/My Drive/Colab Notebooks/Code Warriors - 21 Days ML/Model1-CarPricePrediction-Day10/car_data.csv')
dataset=pd.read_csv('gdrive/My Drive/Colab Notebooks/Code Warriors - 21 Days ML/Model1-CarPricePrediction-Day10/car_data.csv')

# UNDERSTADING DATA

In [ ]:
# string_data.sample(5)         # sample show random 5 row from top to bottom
# string_data.head()          # head show 5 row from top
data.info()
data.shape

NameError: ignored

# DATA PREPROCESSING 

### removing/handling null value

In [ ]:
# CHECKING NULL VALUE
string_data.isnull().sum()
# REPLACING NULL VALUE COL IF COL CONTAIN NULL VALUE
# string_data['col_name_which_contain_null_value'] = string_data['col-name'].fillna(string_data['col-name'].value_counts().index[0])

name                   0
fuel                   0
seller_type            0
owner                  0
transmission_Manual    0
dtype: int64

### my encoding

In [ ]:
# ENCODING DTYPE OBJECT (STRING)

string_data = data.select_dtypes(include=['object'])
print('>>Before Encoding:\n')
string_data.sample(5)

NameError: ignored

In [ ]:
# ENCODING transmission-COL
string_data['transmission'].value_counts()

In [ ]:
# encoding 2 categorical value using get_dummies() pandas method into 0, 1
string_data = pd.get_dummies(string_data, columns=['transmission'], drop_first=True)
string_data['transmission_Manual'].value_counts()

In [ ]:
# ENCODING owner COL 
string_data['owner'].value_counts()

In [ ]:

# method 1
# df_car_mod['owner'] = df_car_mod['owner'].replace('First Owner', 1)
# df_car_mod['owner'] = df_car_mod['owner'].replace('Second Owner', 2)
# df_car_mod['owner'] = df_car_mod['owner'].replace('Third Owner', 3)
# df_car_mod['owner'] = df_car_mod['owner'].replace('Fourth & Above Owner', 4)

# method 2 
string_owner_data_replace = {"owner": {'First Owner': 1, 'Second Owner': 2, 'Third Owner': 3, 'Fourth & Above Owner': 4, 'Test Drive Car': 5}}
string_data.replace(string_owner_data_replace, inplace=True)

string_data['owner'].value_counts()

In [ ]:
# ENCODING seller_type COL 
string_data['seller_type'].value_counts()

In [ ]:
string_sellerType_data_replace = {"seller_type": {'Individual': 1, 'Dealer': 2, 'Trustmark Dealer': 3}}
string_data.replace(string_sellerType_data_replace, inplace=True)

string_data['seller_type'].value_counts()

In [ ]:
# ENCODING fuel COL 
string_data['fuel'].value_counts()

In [ ]:
string_fuel_data_replace = {"fuel": {'Diesel': 1, 'Petrol': 2, 'CNG': 3, 'LPG': 4,'Electric': 5}}
string_data.replace(string_fuel_data_replace, inplace=True)

string_data['fuel'].value_counts()

In [ ]:
string_data.info()

In [ ]:
print('\n\n>>After Encoding fuel Col:\n')

string_data.sample(5) 

In [ ]:
data.head()

In [ ]:
# MERGE string_data WITH ORIGINAL data
data = data.assign(name=string_data['name'], fuel=string_data['fuel'], seller_type=string_data['seller_type'], transmission=string_data['transmission_Manual'], owner=string_data['owner'])
data.drop(['name'],axis=1,inplace=True)
data.head()

### code warrior encoding
best guide [medium](https://medium.com/bycodegarage/encoding-categorical-data-in-machine-learning-def03ccfbf40) 


In [107]:
X = dataset.iloc[:, [0,1,3,4,5,6,7]]
y = dataset.iloc[:, 2]

In [108]:
X.head()

name  year  ...  transmission         owner
0             Maruti 800 AC  2007  ...        Manual   First Owner
1  Maruti Wagon R LXI Minor  2007  ...        Manual   First Owner
2      Hyundai Verna 1.6 SX  2012  ...        Manual   First Owner
3    Datsun RediGO T Option  2017  ...        Manual   First Owner
4     Honda Amaze VX i-DTEC  2014  ...        Manual  Second Owner

[5 rows x 7 columns]

In [109]:
# Including columns which are of object datatype in modified dataframe
df_car_mod = X.select_dtypes(include=['object'])
# Viewing first few rows of data
df_car_mod.head()

name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

In [110]:
# Checking for any null values present in the dataset
df_car_mod['seller_type'].value_counts()

Individual          3244
Dealer               994
Trustmark Dealer     102
Name: seller_type, dtype: int64

In [111]:
# Encoding fuel_type using get_dummies
df_car_mod = pd.get_dummies(df_car_mod, columns=['fuel','seller_type','transmission'], drop_first=True)

In [112]:
df_car_mod.head(15)

name  ... transmission_Manual
0                     Maruti 800 AC  ...                   1
1          Maruti Wagon R LXI Minor  ...                   1
2              Hyundai Verna 1.6 SX  ...                   1
3            Datsun RediGO T Option  ...                   1
4             Honda Amaze VX i-DTEC  ...                   1
5              Maruti Alto LX BSIII  ...                   1
6         Hyundai Xcent 1.2 Kappa S  ...                   1
7          Tata Indigo Grand Petrol  ...                   1
8          Hyundai Creta 1.6 VTVT S  ...                   1
9          Maruti Celerio Green VXI  ...                   1
10          Chevrolet Sail 1.2 Base  ...                   1
11         Tata Indigo Grand Petrol  ...                   1
12  Toyota Corolla Altis 1.8 VL CVT  ...                   0
13                    Maruti 800 AC  ...                   1
14         Maruti Wagon R LXI Minor  ...                   1

[15 rows x 9 columns]

In [113]:
df_car_mod.dtypes

name                            object
owner                           object
fuel_Diesel                      uint8
fuel_Electric                    uint8
fuel_LPG                         uint8
fuel_Petrol                      uint8
seller_type_Individual           uint8
seller_type_Trustmark Dealer     uint8
transmission_Manual              uint8
dtype: object

In [114]:
# Create a dictionary to find and replace values
dic_to_replace = {"owner": {"First Owner": 1, "Second Owner": 2,"Third Owner": 3,"Fourth & Above Owner": 4,"Test Drive Car":5}}
df_car_mod.replace(dic_to_replace, inplace=True)
# View first few rows of data
df_car_mod['owner'].head()

0    1
1    1
2    1
3    1
4    2
Name: owner, dtype: int64

In [115]:
# Enoding make column using LabelBinarizer
from sklearn.preprocessing import LabelBinarizer
labelbinarizer = LabelBinarizer()
make_encoded_results = labelbinarizer.fit_transform(df_car_mod['name'])

In [116]:
labelbinarizer.classes_

array(['Ambassador CLASSIC 1500 DSL AC', 'Ambassador Classic 2000 Dsz',
       'Ambassador Grand 1800 ISZ MPFI PW CL', ...,
       'Volvo XC 90 D5 Inscription BSIV', 'Volvo XC60 D3 Kinetic',
       'Volvo XC60 D5 Inscription'], dtype='<U58')

In [117]:
# Converting an numpy array into a pandas dataframe
df_make_encoded = pd.DataFrame(make_encoded_results, columns=labelbinarizer.classes_)
# Viewing few rows of data
df_make_encoded.sample(10)

Ambassador CLASSIC 1500 DSL AC  ...  Volvo XC60 D5 Inscription
2069                               0  ...                          0
2807                               0  ...                          0
2816                               0  ...                          0
2382                               0  ...                          0
2605                               0  ...                          0
3433                               0  ...                          0
1612                               0  ...                          0
575                                0  ...                          0
2452                               0  ...                          0
4118                               0  ...                          0

[10 rows x 1491 columns]

In [118]:
dfs = [df_make_encoded,X['year'],X['km_driven'],df_car_mod]

In [119]:
df_car_mod.drop(['name'],axis=1,inplace=True)

In [120]:
df_car_mod.head()

owner  fuel_Diesel  ...  seller_type_Trustmark Dealer  transmission_Manual
0      1            0  ...                             0                    1
1      1            0  ...                             0                    1
2      1            1  ...                             0                    1
3      1            0  ...                             0                    1
4      2            1  ...                             0                    1

[5 rows x 8 columns]

In [121]:
res = pd.concat(dfs,axis=1)

In [122]:
res.head(15)

Ambassador CLASSIC 1500 DSL AC  ...  transmission_Manual
0                                0  ...                    1
1                                0  ...                    1
2                                0  ...                    1
3                                0  ...                    1
4                                0  ...                    1
5                                0  ...                    1
6                                0  ...                    1
7                                0  ...                    1
8                                0  ...                    1
9                                0  ...                    1
10                               0  ...                    1
11                               0  ...                    1
12                               0  ...                    0
13                               0  ...                    1
14                               0  ...                    1

[15 rows x 1501 columns]

# SPLITTING DATASET 

###my splitting

In [ ]:
# data 
data.head()

year  selling_price  km_driven  fuel  seller_type  transmission  owner
0  2007          60000      70000     2            1             1      1
1  2007         135000      50000     2            1             1      1
2  2012         600000     100000     1            1             1      1
3  2017         250000      46000     2            1             1      1
4  2014         450000     141000     1            1             1      2

In [ ]:
# defining feature and label ac to problem objective
# objective is to predict selling price of car when given data (name, year, km_driven, fuel, seller_type, transmission, owner)
# x is feature (independent variable), y is label (dependent variable (prediction variable))

X = data.iloc[:, [0,2,3,4,5,6]]
Y = data.iloc[:, [1]]

# X.head()
Y.sample(5)

selling_price
311          106000
4003         260000
3529         470000
568          385000
1772         350000

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X.values, Y.values, test_size = 0.2, random_state = 0)

print('>> TESTING DATA-SET:')
print('\nfeature',x_train)
print('\nlabels', y_train)

# print('\n>> TRAINING DATA-SET:')
# print('\nfeature', x_test.head())
# print('\nlabels', y_test.head())

>> TESTING DATA-SET:

feature [[  2015 175000      1      1      1      1]
 [  2012 170000      1      1      1      1]
 [  2006 110000      2      1      1      1]
 ...
 [  2016  22000      2      1      1      1]
 [  2015  70000      1      1      1      1]
 [  2013  62000      2      1      1      2]]

labels [[300000]
 [600000]
 [ 95000]
 ...
 [270000]
 [600000]
 [229999]]


### code warrior splitting

In [78]:
import numpy as np

In [96]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

x = res

x = x.values
y = y.values

print(x[0:5, :])
print(y)

[[0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]]
[ 60000 135000 600000 ... 110000 865000 225000]


In [106]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

print('training dataset \n')
print('> ', x_train.shape, y_train.shape)
print(x_train[0:5,:])
print(y_train)

print('\ntesting dataset \n')
print('> ', x_test.shape, y_test.shape)
print(x_test[0:5,:])

# y_test = np.argmax(y_test, axis=1)

training dataset 

>  (3472, 1501) (3472,)
[[0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 1]]
[300000 600000  95000 ... 270000 600000 229999]

testing dataset 

>  (868, 1501) (868,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]]


# APPLYING DIFFERENT REGRESSION LEARNING ALGORITHM

In [ ]:
import numpy as np
import time

In [ ]:
# LINEAR REGRESSION / MULTIPLE LINEAR REGRESSION
start = time.clock()

from sklearn.linear_model import LinearRegression

linear_regressor = LinearRegression()

model = linear_regressor.fit(x_train, y_train)

print('model created successfully')

# y_pred = model.predict(x_test)

accuracy = model.score(x_test,y_test)
print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')

model created successfully
accuracy:  -25223325713134.62 %
time taken:  3 sec


In [ ]:
# POLYNOMIAL REGRESSION

from sklearn.preprocessing import PolynomialFeatures
start = time.clock()

polynomial_regressor = PolynomialFeatures(degree=3)

x_poly = polynomial_regressor.fit_transform(x_train)

linear_regressor = LinearRegression()

model = linear_regressor.fit(x_poly, y_train)

print('model created successfully')

accuracy = model.score(x_test,y_test)
print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')

In [ ]:
# SUPPORT VECTOR REGRESSION 

from sklearn.svm import SVR
start = time.clock()

sv_regressor = SVR(kernel='rbf')

model = sv_regressor.fit(x_train, y_train)

print('model created successfully')

accuracy = model.score(x_test,y_test)
print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')

model created successfully
accuracy:  -8.559892120349755 %
time taken:  38 sec


In [ ]:
# DECISION TREE 

from sklearn.tree import DecisionTreeRegressor
start = time.clock()

dt_regressor = DecisionTreeRegressor(random_state=0)

model = dt_regressor.fit(x_train, y_train)

print('model created successfully')

accuracy = model.score(x_test,y_test)
print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')

model created successfully
accuracy:  62.483557292135984 %
time taken:  0 sec


In [ ]:
# RANDOM FOREST 

from sklearn.ensemble import RandomForestRegressor
start = time.clock()

rd_regressor = RandomForestRegressor(n_estimators=10, random_state=0)

print('shape of training dataset: ',x_train.shape, y_train.shape)

model = rd_regressor.fit(x_train, y_train) 

print('model created successfully')

y_test = y_test.reshape(-1, 1)

y_pred = model.predict(x_test)

y_pred = y_pred.reshape(-1, 1)

print('shape of testing dataset: ',x_test.shape, y_test.shape)
print(y_pred.shape, y_test.shape)


accuracy = model.score(y_pred, y_test)
# print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')

shape of training dataset:  (3472, 1501) (3472, 1)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


model created successfully
shape of testing dataset:  (868, 1501) (868, 1)
(868, 1) (868, 1)


ValueError: ignored

In [ ]:
# RANDOM FOREST - CODE WARRIOR

from sklearn.ensemble import RandomForestRegressor
start = time.clock()

regressor = RandomForestRegressor(n_estimators=300,random_state=0)

model = regressor.fit(x_train,y_train)

print('model created successfully')

accuracy = model.score(x_test,y_test)
print('accuracy: ',accuracy*100,'%')

print('time taken: ', int(time.clock() - start), 'sec')



```
new_data=["Maruti 800 AC",2007,70000,"Petrol","Individual","Manual","First Owner"]
new_data=pd.DataFrame(new_data)
new_data_mod = new_data.select_dtypes(include=['object'])
new_data_mod=new_data_mod.T
print(new_data_mod)


y_pred = model.predict(x_test)

# print(y_pred, y_test)
```

